all:
  vars:
    ansible_user: deploy
    ansible_port: 2222
  children:
    managers:
      hosts:
        manager-1:
          ansible_host: 62.238.34.57
    workers_app:
      hosts:
        manager-1:
    workers_data:
      hosts:
        worker-db-1:
          ansible_host: 62.238.46.245
        worker-redis-1:
          ansible_host: 62.238.36.18