all:
  vars:
    ansible_user: deploy
    ansible_port: 2222
  children:
    managers:
      hosts:
        manager-1:
          ansible_host: <IP_MANAGER_1_STAGING>
    workers_app:
      hosts:
        worker-app-1:
          ansible_host: <IP_WORKER_APP_1_STAGING>
        worker-app-2:
          ansible_host: <IP_WORKER_APP_2_STAGING>
    workers_data:
      hosts:
        worker-data-1:
          ansible_host: <IP_WORKER_DATA_1_STAGING>