all:
  children:
    managers:
      hosts:
        manager-1:
          ansible_host: <IP_MANAGER_1_STAGING>
          ansible_user: deploy 
    workers_app:
      hosts:
        worker-app-1:
          ansible_host: <IP_WORKER_APP_1_STAGING>
          ansible_user: deploy
        worker-app-2:
          ansible_host: <IP_WORKER_APP_2_STAGING>
          ansible_user: deploy
    workers_data:
      hosts:
        worker-data-1:
          ansible_host: <IP_WORKER_DATA_1_STAGING>
          ansible_user: deploy